site_name: Fish and Deer的个人网站
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - content.tabs.link
nav:
  - 这是我: index.md
  - 博客: blog.md
  - 项目经历: project.md
  - 好用工具: tools.md
  - paper: paper.md
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.details

extra_css:
  - assets/extra.css

